### ISSUE TITLE
share codes which you think are useful in practising -- It can be of any language / framework.

### ISSUE THREAD

**Issue by Aman1440** [Aman1440/Practice-code-repo#1]
Aim:

-To help first-time contributors in this hacktober fest by giving up a simple task of contributing their codes to this world of open-source.

-To make a reference which would help everyone who is preparing for placements or starting up a new language to learn and code 
easily and get a few reference problems.

**Comment by Aman1440** [comment]
This issue will be getting closed on this sunday date- 04/ 10/ 2020

**Comment by Sukanya41455** [comment]
@all-contributors please add Sukanya41455 for cpp_codes

**Comment by Sukanya41455** [comment]
@all-contributors please add Sukanya41455 for cpp codes
