### ISSUE TITLE
Need a code of conduct for the contributors!

### ISSUE THREAD

**Issue by Aman1440** [Aman1440/Practice-code-repo#3]
If you think you can contribute to writing COC you can mail to - aman78871440@gmail.com and i'll assign it to you,
or you can comment here too.

**Comment by Sukanya41455** [comment]
### CODE OF CONDUCT

By participating, you agree to abide by the following code of conduct.

- Please treat all the participants with the utmost respect. Behave professionally, and do not insult or put down other attendees. Any kind of harassment will not be tolerated and if you see such activities kindly report to the hackathon organizer.

-  All the designed code must be your own and must be created during the event, plagiarism is strictly prohibited.

**Comment by Aman1440** [comment]
hey @Sukanya41455 ,
Thanks for the comment. it would be great if you can make a pull request.

**Comment by ayushi-1408** [comment]
Hey I would like to do this issue.

**Comment by Aman1440** [comment]
hii @ayushi-1408 ,
I am assigning the task to you, please try to complete it asap.

-- Others who want to contribute to read.me can reach out to me at - aman78871440@gmail.com

**Comment by Aman1440** [comment]
The issue is resolved and there is no further need for changes. However, if anyone thinks or has an idea of modifying you can mail me at - aman78871440@gmail.com.
