### ISSUE TITLE
Know git n github--- Add a folder which helps to learn git n github commands.

### ISSUE THREAD

**Issue by Aman1440** [Aman1440/Practice-code-repo#5]
Need a folder with the content of git and GitHub --- 

- It would help everyone understand the functions of Git and how to use github.

**Comment by vikramoff24** [comment]
We'll be working on it !

**Comment by Aman1440** [comment]
Hello @vikramoff24,
I'll be assigning you this task.
Thanks-regards,
@Aman1440

**Comment by vikramoff24** [comment]
Okay Aman. I'll start working on it

**Comment by vikramoff24** [comment]
Added git command for syncing fork repo with it's master.

**Comment by Aman1440** [comment]
Merged it.

Happy hacktober.

**Comment by Aman1440** [comment]
I'll keep this issue open for enhancements in readme now.
thanks.
