### ISSUE TITLE
In Read.me add git commands to pull and push the repo.

### ISSUE THREAD

**Issue by Aman1440** [Aman1440/Practice-code-repo#58]

**Comment by VARhimank** [comment]
Can I do that ? Please assign

**Comment by hnishal** [comment]
@Aman1440 assign me the issue

**Comment by Aman1440** [comment]
already merged thanks. maybe you can add up the example command (to make it more simple for the new ones to know git ). or anything which makes it more simpler.

**Comment by hnishal** [comment]
@Aman1440 
should i add stat button in Readme?

**Comment by vikramoff24** [comment]
Added for syncing fork repo with it's master.

**Comment by Aman1440** [comment]
can you mail me -- describing whatever idea you have. Thanks.
--

aman78871440@gmail.com

**Comment by Aman1440** [comment]
Got the mail and have replied too.

You can send a pr with suggested changes.

**Comment by hnishal** [comment]
Yeah, Im working on it.
