### ISSUE TITLE
Add a folder with GO language programs.

### ISSUE THREAD

**Issue by Aman1440** [Aman1440/Practice-code-repo#59]
#59 th issue .

**Comment by limaleandro1999** [comment]
@Aman1440 Can I work on this issue?

**Comment by Aman1440** [comment]
Yes, All the best.

I'll be assigning it to you.

Other than @limaleandro1999 if anyone else is interested in working on this issue #59 you can comment down or mail to know more about the issue - aman78871440@gmail.com

**Comment by limaleandro1999** [comment]
PR: https://github.com/Aman1440/Practice-code-repo/pull/67

**Comment by Aman1440** [comment]
yepp, Already merged.

However the issue will be kept open for other contributors to merge to contribute more programs.
