### ISSUE TITLE
Need a folder with programs of dart.

### ISSUE THREAD

**Issue by Aman1440** [Aman1440/Practice-code-repo#61]
#61

**Comment by sahastrakishore123** [comment]
I would like to work on this as a part of Hacktoberfest. Can you assign me to do so?

**Comment by Aman1440** [comment]
Yes, all the best.

If anyone else is interested to contribute to this issue number #61 can comment down or mail to aman78871440@gmail.com.
Thanks.

**Comment by sahastrakishore123** [comment]
I have made a PR Kindly Look into it. @Aman1440

**Comment by Aman1440** [comment]
The folder is made and now we need to add programs from the basic level to the expert.
Thanks, @sahastrakishore123 for your contribution.
I'll be opening up this issue to add more programs so if anyone is interested can reach to me at aman78871440@gmail.com or comment down.

Thanks.
