### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by AkshayaKulasekaran** [Aman1440/Practice-code-repo#7]
I noticed that there are a few places where the readme.md could be better worded. I'd like to make a few changes to it, restructuring it and the such

**Comment by Aman1440** [comment]
hey @AkshayaKulasekaran ,
you can send a pull request with all the changes you think you can make to make the README.md better, will review it and merge if the changes are making things better.

**Comment by AkshayaKulasekaran** [comment]
Sure thing!
