### ISSUE TITLE
work on broken links.

### ISSUE THREAD

**Issue by Aman1440** [Aman1440/Practice-code-repo#94]
there are few broken links, it would be great if someone can work on them.

**Comment by hnishal** [comment]
yeah, i will work on it
and the contributor thing, follow this link add the bot on main repo
https://allcontributors.org/docs/en/bot/overview

**Comment by Aman1440** [comment]
okay, I'll assign you the task for working on broken links.

thanks for the link, my team is working on it.

**Comment by hnishal** [comment]
Yeah, if you habe troubles figuring it out. I'll guide you through
